#!/python3
#Palindrome string

string = input('Enter a string: ')
reverse = string[::-1]

if string == reverse:
    print('The string you entered is palindrome')
else:
    print('The string you entered is not palindrome')
