#!/python3

import random
# A function that simulates a roll of two dice
# @return summary the added result of the roll
def rolling_the_dice():

	d1 = random.choice(range(1,7))
	d2 = random.choice(range(1,7))
	summary = d1 + d2
	return summary

if __name__ == '__main__':
	table = {}
	# A list that each index represent a number from 2 to 12 
	# and its value is the number of times this total has occured
	n = [0,0,0,0,0,0,0,0,0,0,0]
	# simulating 1.000 rolls of two dice
	for i in range (0,1000):
		number = rolling_the_dice()
		# Counting the number of times a total has occured
		for i in range(0,11):
			if number == i + 2:
				n[i] += 1
	# A list with the expected percent of each total
	expected_p = [2.78, 5.56, 8.33, 11.11, 13.89, 16.67, 13.89, 11.11, 8.33, 5.56, 2.78]
	# Adding the header to the table
	table[0] = ['Total','Simulated Percent', 'Expected percent']
	# Adding the total, the simpulated percent and the expected percent to the table
	for i in range(1,12):
		table[i] = ['  ' + str(i + 1),'            ' + str(n[i-1]/10), '            ' + str(expected_p[i-1])]
	# Printing the values of the table one line at a time
	for key in table:
		print(table[key])
	




	

