#!/python3
i = True
counter = 0
while i == True:
    string_input = input('Enter a number: ') 
    # Checking if input is a number
    try:
        number = float(string_input) 
        counter += number
        print(counter)
    except ValueError:
        # Checking if input is a blank line
        if string_input == '':
            break