#!/python3
import string

# A function that checks which characters and how many times appear in a string 
# @param user_input a string to check 
# @return occurence a dict that 
def character_check(user_input):
	# Creating a dict
	occurence = {}
	for i in string.printable:
		occurence[i] = 0
	user_input = user_input.lower()
	# If a character exist its value is updated
	for i in user_input:
		occurence[i] += 1
	return occurence


if __name__ == '__main__':
	# user input
	first_string = input('Enter first string: ')
	second_string = input('Enter second string: ')
	# If the strings use the same characters both in kind and number are anagrams
	if character_count(first_string) == character_count(second_string):
		print('The strings are anagrams')
	else:
		print('The strings are not anagrams')