#!/python3
import random
import pandas as pd
# A function that generates a BINGO card
# @return card a dictionary that represents a random BINGO card
def bingo_card():
	card = {}
	a = 0
	for i in 'BINGO':
		card[i] = []
		for x in range(0,5):
			range_ = []
			for y in range(1,16):
				range_.append(y + a * 15)
			card[i].append(random.choice(range_))
		a += 1
	return card
# A function that displays a BINGO card in columns
# @param c a dictionary that represents the card to display
# @return table a string that displays the @param in columns
def display_card(c):
	table = pd.DataFrame(c)
	return table.to_string(index=False)
	
print('Here is your BINGO card:')
print(display_card(bingo_card()))
