#!/python3
import sys
# A Python program that reads one or more Python source files and identifies functions that are not immediately preceded by a comment

# A function that identifies if a function is preceded by a comment
# @param filename the name of the file provided in the command line
def missing_comments(filename):
	f = open(filename, 'r')
	line_list = f.readlines()
	f.close()
	prev_line = ''
	for line in line_list:
		# Testing if a function is preceded by a comment
		if line.startswith('def') and not(prev_line.startswith('#')):
			# Getting the line number
			index = line_list.index(line) + 1
			# Getting the function name
			words = line.split()
			function_name = words[1]
			function_name = function_name.split('(')
			prev_line = line
			# Printing the output
			print('In file {}, funtion {} in line {} is missing comments'.format(filename, function_name[0], index))

if __name__ == '__main__':
	# Going through the command line arguments	
	for i in range(len(sys.argv) - 1):
		try:
			file = sys.argv[i + 1]
			missing_comments(file)
		except Exception as e:
			print(e)
