#!/python3
# Declaring a global variable
total = 0
# A recursive function that sums values from the user
def recursive_total():
	global total
	value = input('Enter a value (blank to quit): ')
	if value != '':
		total += float(value)
		recursive_total()
	else:
		return

if __name__ == '__main__':
	value0 = input('Enter a value (blank to quit): ')
	if value0 == '':
		print('0.0')
	else:
		total += float(value0)
		recursive_total()
		print(total)



