#!/python3
import sys
import re
import string
print('This is a program that redacts all occurrences of sensitive words in a text file by replacing them with asterisks')
# User input
or_file = open(input('Enter the name of the file you want test for sensitive words: '), 'r')
sens_file = open(input('Enter the name of the file that contains the words to redact: '), 'r')
name = input('How you want to name the redacted file?: ')
new_file = open(name, 'w')
# Making the list of sensitive words
w_list = []
sens_list = sens_file.readlines()
sens_file.close()
for line in sens_list:
    for word in line.split():
        word = (''.join(filter(str.isalpha, word))).upper()
        w_list.append(word)
# Reading the original file
or_file_lines = or_file.readlines()
for line in or_file_lines:
    # Testing if a new line was inserted
    res = bool(re.search(r"\n", line))
    if res == True:
        flag = True
    else:
        flag = False
    # Spliting the line into words 
    for word in line.split():
        og_word = word
        word = (''.join(filter(str.isalpha,word))).upper()
        for w in w_list:
                if w in word:
                # Replacing a sensitive word with asterisks
                    new_w = '' 
                    for ch in w:
                        new_w += '*'
                    # Writing asterisks to the new file if it's not sensitive
                    word = word.replace(w, new_w)
        # Creating the word to write in the new file
        new_str = ''
        for i in range(len(word)):
            if word[i] == og_word[i]:
                new_str += word[i]
            elif word[i] == '*':
                new_str += word[i]
            else:
                new_str += og_word[i]
        # Testing if the original word had punctuation
        for char in og_word:
            if char in string.punctuation:
                new_str += char
        new_file.write(new_str + ' ')
    # inserting a new line if there was one in the original file
    if flag == True:
        new_file.write('\n')
or_file.close()
new_file.close()