#!/python3

#Maximum integer

import random as r

list = []
for i in range(1,101):
    list.append(i)

number = r.choice(list)
counter = 0
print (number)

for i in range(1,100):
    x = r.choice(list)
    if x>number:
        number = x
        counter += 1
        print (x, '  <== Update')
    else:
        print (x)

print ("The maximun value found was ",number)
print ("The maximum value was updated ",counter, 'times')

